# ============================================================================
# DISCORD BOT LAUNCHER
# ============================================================================
#
# This script starts your Discord bot and automatically loads all runtime cogs.
#
# WHAT DOES THIS SCRIPT DO?
# - Reads configuration from config.json and variables.py
# - Starts the Discord bot
# - Scans the /cogs folder for available runtime modules
# - Loads all found cogs automatically
# - Provides clear feedback about what's being loaded
#
# HOW TO ADD NEW FEATURES?
# 1. Create a new .py file in the /cogs folder (NOT setup_cogs!)
# 2. Make sure it has a setup() function
# 3. Restart this launcher
# 4. The cog will be automatically detected and loaded!
#
# DIFFERENCE BETWEEN /cogs AND /setup_cogs:
# - /cogs: Runtime features (moderation, welcome, fun commands, etc.)
#          These are loaded by THIS launcher and run 24/7
# - /setup_cogs: One-time setup scripts (server builder, database init, etc.)
#                These are only used by setup_server.py during initial setup
#
# HOW TO START THE BOT:
# 1. Open terminal/command prompt
# 2. Navigate to this folder: cd path/to/discord-server-setup
# 3. Run: python launcher.py
# 4. The bot starts automatically!
#
# HOW TO STOP THE BOT:
# - Press Ctrl+C in the terminal
#
# TROUBLESHOOTING:
# - Bot won't start? Check your bot token in config.json or variables.py
# - Cog won't load? Look at the error messages below
# - Permission issues? Check bot permissions in Discord Developer Portal
#
# ============================================================================

import asyncio
import discord
from discord.ext import commands
import json
import sys
from pathlib import Path
import traceback
from datetime import datetime
import importlib.util

# ============================================================================
# IMPORT UTILITIES
# ============================================================================

# Add current directory to Python path
sys.path.insert(0, str(Path(__file__).parent))

try:
    from utils.logger import setup_logger, log_startup, log_shutdown
    logger = setup_logger("launcher")
except ImportError:
    # Fallback to basic logging if utils not available
    import logging
    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger("launcher")
    log_startup = lambda: None
    log_shutdown = lambda: None

try:
    from variables import (
        BOT_TOKEN,
        GUILD_ID,
        COMMAND_PREFIX,
        BOT_STATUS,
        BOT_STATUS_TYPE,
        COGS_DIR,
        CONFIG_FILE,
        validate_config,
    )
except ImportError:
    logger.error("❌ ERROR: variables.py not found!")
    logger.error("   Please ensure variables.py exists in the same directory")
    sys.exit(1)

# ============================================================================
# CONFIGURATION LOADING
# ============================================================================

def load_config():
    """
    Loads configuration from config.json
    
    This file is generated by setup.ps1 and contains server-specific settings
    
    Returns:
        dict: Configuration data with bot token and server settings
    """
    try:
        if not CONFIG_FILE.exists():
            logger.warning("⚠️  WARNING: config.json not found!")
            logger.warning(f"   Expected location: {CONFIG_FILE}")
            logger.warning("   Using values from variables.py only")
            return {}
        
        with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
            config = json.load(f)
        
        logger.info("✅ Configuration loaded from config.json")
        return config
        
    except json.JSONDecodeError as e:
        logger.error(f"❌ ERROR: config.json is not valid JSON format")
        logger.error(f"   Details: {e}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"❌ ERROR: Could not load configuration")
        logger.error(f"   Details: {e}")
        sys.exit(1)

# ============================================================================
# COG DISCOVERY (RUNTIME COGS ONLY)
# ============================================================================

def discover_cogs(cogs_dir: Path):
    """
    Scans the /cogs folder and finds all available runtime cog modules
    
    NOTE: This ONLY scans /cogs, NOT /setup_cogs!
    Setup cogs are only used during initial server setup.
    
    Args:
        cogs_dir (Path): Path to the cogs folder
        
    Returns:
        list: List of cog names (without .py extension)
    """
    logger.info("\n🔍 Scanning for runtime cogs...")
    logger.info(f"   Location: {cogs_dir}")
    logger.info("-" * 60)
    
    if not cogs_dir.exists():
        logger.warning(f"⚠️  WARNING: Cogs folder not found: {cogs_dir}")
        logger.warning("   Creating folder... Place your cog files there")
        cogs_dir.mkdir(parents=True, exist_ok=True)
        return []
    
    discovered_cogs = []
    
    # Scan all .py files in the cogs folder
    for file_path in sorted(cogs_dir.glob("*.py")):
        # Skip private files (start with _)
        if file_path.stem.startswith("_"):
            logger.debug(f"⏭️  Skipping: {file_path.name} (private file)")
            continue
        
        # Validate that it's a proper cog
        if validate_cog_file(file_path):
            discovered_cogs.append(file_path.stem)
            logger.info(f"✅ Found: {file_path.stem}")
        else:
            logger.warning(f"⚠️  Invalid: {file_path.stem} (missing setup function)")
    
    logger.info("-" * 60)
    logger.info(f"📦 Total runtime cogs discovered: {len(discovered_cogs)}\n")
    
    return discovered_cogs

def validate_cog_file(file_path: Path):
    """
    Checks if a Python file is a valid cog
    
    A valid cog must have a setup() or async setup() function
    
    Args:
        file_path (Path): Path to the Python file
        
    Returns:
        bool: True if it's a valid cog
    """
    try:
        # Read the file content
        content = file_path.read_text(encoding='utf-8')
        
        # Check for setup function (basic validation)
        # More advanced: Could import and inspect the module
        if 'def setup(' in content or 'async def setup(' in content:
            return True
        
        return False
        
    except Exception as e:
        logger.debug(f"   Error validating {file_path.name}: {e}")
        return False

# ============================================================================
# BOT INITIALIZATION
# ============================================================================

def create_bot(config: dict):
    """
    Creates and configures the Discord bot instance
    
    Args:
        config (dict): Configuration data from config.json
        
    Returns:
        commands.Bot: Configured bot instance
    """
    logger.info("🤖 Initializing bot...")
    
    # Intents determine which Discord events the bot can receive
    # Intents.all() gives access to all events (members, messages, etc.)
    intents = discord.Intents.all()
    
    # Create bot instance
    # command_prefix: The character for commands (e.g., !help)
    # intents: Which Discord events the bot may receive
    # help_command=None: Disable default help command (create your own!)
    bot = commands.Bot(
        command_prefix=COMMAND_PREFIX,
        intents=intents,
        help_command=None
    )
    
    # Add custom attributes to bot instance
    bot.config = config
    bot.start_time = datetime.utcnow()
    bot.server_name = config.get('server', {}).get('name', 'Unknown Server')
    bot.guild_id = config.get('server', {}).get('guild_id', GUILD_ID)
    
    logger.info(f"✅ Bot initialized")
    logger.info(f"   Server: {bot.server_name}")
    logger.info(f"   Prefix: {COMMAND_PREFIX}")
    logger.info(f"   Guild ID: {bot.guild_id}\n")
    
    return bot

# ============================================================================
# COG LOADING
# ============================================================================

async def load_cogs(bot: commands.Bot, cog_list: list):
    """
    Loads all runtime cogs into the bot
    
    Args:
        bot (commands.Bot): The bot instance
        cog_list (list): List of cog names to load
    """
    logger.info("📥 Loading runtime cogs...")
    logger.info("-" * 60)
    
    loaded_count = 0
    failed_count = 0
    
    for cog_name in cog_list:
        try:
            # Load extension (cog)
            # Format: cogs.CogName (folder.filename)
            await bot.load_extension(f"cogs.{cog_name}")
            logger.info(f"✅ Loaded: {cog_name}")
            loaded_count += 1
            
        except commands.ExtensionNotFound:
            logger.error(f"❌ Failed: {cog_name} (not found)")
            failed_count += 1
        except commands.ExtensionAlreadyLoaded:
            logger.warning(f"⚠️  Warning: {cog_name} (already loaded)")
        except commands.NoEntryPointError:
            logger.error(f"❌ Failed: {cog_name} (no setup function)")
            failed_count += 1
        except commands.ExtensionFailed as e:
            logger.error(f"❌ Failed: {cog_name}")
            logger.error(f"   Error: {e}")
            failed_count += 1
        except Exception as e:
            logger.error(f"❌ Failed: {cog_name}")
            logger.error(f"   Unexpected error: {e}")
            traceback.print_exc()
            failed_count += 1
    
    logger.info("-" * 60)
    logger.info(f"✅ Successfully loaded: {loaded_count}")
    if failed_count > 0:
        logger.warning(f"❌ Failed to load: {failed_count}")
    logger.info("")

# ============================================================================
# BOT EVENTS
# ============================================================================

def setup_events(bot: commands.Bot):
    """
    Registers event handlers for the bot
    
    Events are actions that Discord triggers (e.g., bot is online, message received)
    """
    
    @bot.event
    async def on_ready():
        """
        Triggered when the bot successfully connects to Discord
        """
        logger.info("=" * 60)
        logger.info("🎉 BOT IS ONLINE!")
        logger.info("=" * 60)
        logger.info(f"Bot Name:     {bot.user.name}")
        logger.info(f"Bot ID:       {bot.user.id}")
        logger.info(f"Server:       {bot.server_name}")
        logger.info(f"Guild ID:     {bot.guild_id}")
        logger.info(f"Cogs Loaded:  {len(bot.cogs)}")
        logger.info(f"Latency:      {round(bot.latency * 1000)}ms")
        logger.info(f"Prefix:       {COMMAND_PREFIX}")
        logger.info("=" * 60)
        
        # Set bot status (what it shows as "Playing...")
        try:
            activity_type = {
                'playing': discord.ActivityType.playing,
                'watching': discord.ActivityType.watching,
                'listening': discord.ActivityType.listening,
                'competing': discord.ActivityType.competing,
            }.get(BOT_STATUS_TYPE.lower(), discord.ActivityType.watching)
            
            activity = discord.Activity(type=activity_type, name=BOT_STATUS)
            await bot.change_presence(activity=activity)
            logger.info(f"✅ Status set: {BOT_STATUS_TYPE.title()} {BOT_STATUS}")
        except Exception as e:
            logger.warning(f"⚠️  Could not set bot status: {e}")
        
        # Sync slash commands with Discord
        try:
            if bot.guild_id:
                guild = discord.Object(id=int(bot.guild_id))
                bot.tree.copy_global_to(guild=guild)
                await bot.tree.sync(guild=guild)
                logger.info("✅ Slash commands synced")
        except Exception as e:
            logger.warning(f"⚠️  Could not sync slash commands: {e}")
        
        logger.info("\n✨ Bot is ready to use!\n")
    
    @bot.event
    async def on_command_error(ctx, error):
        """
        Triggered when a command raises an error
        
        Args:
            ctx: Context of the command
            error: The error that occurred
        """
        # Ignore "command not found" errors
        if isinstance(error, commands.CommandNotFound):
            return
        
        # Missing permissions
        if isinstance(error, commands.MissingPermissions):
            await ctx.send("❌ You don't have permission to use this command!")
            return
        
        # Missing arguments
        if isinstance(error, commands.MissingRequiredArgument):
            await ctx.send(f"❌ Missing required argument: `{error.param.name}`")
            return
        
        # Command on cooldown
        if isinstance(error, commands.CommandOnCooldown):
            await ctx.send(f"⏰ This command is on cooldown. Try again in {error.retry_after:.1f}s")
            return
        
        # Log other errors
        logger.error(f"❌ Command error in {ctx.command}: {error}")
        logger.error(traceback.format_exception(type(error), error, error.__traceback__))
        
        # Send generic error message to user
        await ctx.send("❌ An error occurred while executing this command.")
    
    @bot.event
    async def on_error(event, *args, **kwargs):
        """
        Triggered when a non-command error occurs
        
        Args:
            event: The event that caused the error
        """
        logger.error(f"❌ Error in event {event}")
        logger.error(traceback.format_exc())

# ============================================================================
# MAIN LAUNCHER
# ============================================================================

async def main():
    """
    Main function that starts the bot and keeps it running
    """
    print("\n" + "=" * 60)
    print("  DISCORD BOT LAUNCHER - RUNTIME MODE")
    print("=" * 60 + "\n")
    
    # Start logging
    log_startup()
    
    # 1. Validate configuration from variables.py
    logger.info("🔍 Validating configuration...")
    config_errors = validate_config()
    if config_errors:
        logger.error("❌ Configuration errors found:")
        for error in config_errors:
            logger.error(f"   - {error}")
        logger.error("\nPlease fix these errors in variables.py")
        sys.exit(1)
    logger.info("✅ Configuration valid\n")
    
    # 2. Load config.json (optional, contains server-specific settings)
    config = load_config()
    
    # 3. Determine bot token (config.json overrides